receivers:
  otlp:
    protocols:
      grpc:
exporters:
  otlp:
    endpoint: "apm-server:8200" 
    tls:
      insecure: true 

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      exporters: [otlp]