receivers:
  otlp:
    protocols:
      grpc:
      http:
    
processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 2000
  batch:
  
exporters:
  otlp:
    endpoint: "es-cluster-fleet-server-1:8200"
    tls:
      insecure: true
    headers:
      Authorization: "Bearer supersecrettoken"
      compression: none
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors : [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors : [batch]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]